Add "Dans une galaxie près de chez vous" and "District 31" categories
eepp/qngng pull request #4
Opened 2020-10-27 14:38 UTC by frdeso

2020-10-27 16:44 UTC, eepp requested changes
Thank you for your contribution!

Much apprécié.

Can you compress the JSON files encore plus? A pass through `jq -c` devrait aider.

Marci!

2020-10-27 16:44 UTC, eepp commented on qngng/qngng.py
> +    elif fullname.middle_name is None:
This is becoming hard to read.

Can we have parts instead?

1. Start with an empty list named `parts`.
2. If there's a name, append it to the list.
3. If there's a middle name/initial, append it to the list (using the very sophisticated algorithm which is already there).
4. If there's a surname, append it to the list.
5. Let `raw_name` be `' '.join(parts)`.

2020-10-27 18:14 UTC, frdeso commented on qngng/qngng.py
> +    elif fullname.middle_name is None:
done.

2020-10-28 02:17 UTC, merged

2020-10-28 02:17 UTC, eepp commented
👌